# call_api.py

# Necessary Imports
from fyers_api import fyersModel
import pickle

# Load the token from Pickle file generated by create_access_token.py file
with open('fyers_token.pickle', 'rb') as f:
    token = pickle.load(f)

is_async = False  # (By default False, Change to True for asnyc API calls.)

# Create Model
fyers = fyersModel.FyersModel(is_async)

# Check your Profile
print (fyers.get_profile(token=token))

# Check Funds
print(fyers.funds(token=token))

# Check Holdings
print(fyers.holdings(token=token))
